### ISSUE TITLE
inliner adds second xmlns attribute to head

### ISSUE THREAD

**Issue by ArloL** [zurb/foundation-emails#110]
The Ink Inliner (http://zurb.com/ink/inliner.php) duplicates the xmlns attribute on the html tag. Try it with one of the templates and you will see
~~~
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
~~~
instead of
~~~
<html xmlns="http://www.w3.org/1999/xhtml">
~~~

**Comment by andrewblake1** [comment]
I see the same was mentioned and closed in https://github.com/zurb/ink/issues/40 as not causing any issues.

Note that it is an issue for php's DOMDocument loadHTML method which rejects the templates because of this. The work around is to manually edit the result of the Ink inliner before storing the templates.

Thanks though for this great product - has been a lot of help to me.

**Comment by tdhartwick** [comment]
We've updated our inliner which should address this issue. Let us know if this is still an issue in our new version!
