### ISSUE TITLE
Gmail not responsive

### ISSUE THREAD

**Issue by CharlJKruger** [zurb/foundation-emails#134]
I've read up and searched for a solution for like a month with ink to make the templates responsive on gmail though its all bits of scattered info.. and can't put it together.

Could you please do like the http://zurb.com/ink/downloads/templates/sidebar.html template and explain what was needed in order to make it responsive on gmail?

Please :)

**Comment by raviedavie** [comment]
I've not been able to get Ink to behave as suggested in the docs either. I've posted on the Zurb forum but not had a reply.

I have found a solution that does work in Gmail but it requires Ink to be modified. This is where I found the solution. I've created something of my own which is a hybrid of these.

https://www.campaignmonitor.com/blog/post/4240/creating-a-centred-responsive-design-without-media-queries
http://webdesign.tutsplus.com/articles/creating-a-simple-responsive-html-email--webdesign-12978

This is probably not what you want but my be the best for gmail.
http://blog.fogcreek.com/responsive-html-emails-a-different-strategy/

Hope this helps.

**Comment by CharlJKruger** [comment]
@raviedavie could you please provide an example of the modified code? Would really help and thank you

**Comment by CharlJKruger** [comment]
I have gone through all the github issues, all the stack overflow related ink + gmail questions and still cant find anything. Please help

**Comment by rafibomb** [comment]
@raviedavie  Can you link your forum post for help?

**Comment by NelsonScott** [comment]
+1

**Comment by LucasKA** [comment]
It's clearly stated in the Ink docs that Media Queries are not supported in Gmail and that the solution is to use the block-grid.

block-grid sucks in a different way, but thats whats going down.

![guise](http://www.reactionface.info/sites/default/files/imagecache/Node_Page/images/1310497097772.gif)

**Comment by tdhartwick** [comment]
Our apologies for the confusion. To better phrase what's going on with gmail and the block-grid is: To fake a responsive email on gmail, you can use the block-grid to achieve this.

Basically, the block-grid can be used in gmail, since it is inline-block, and things can stack on top of each other if they run out of space. 

There are more complicated approaches to achieve a truly responsive email in gmail, however, we chose to pursue a less complicated codebase and in hopes that gmail would support media queries sometime soon (fingers still crossed). With v2, the Inky language gives us some opportunities to offload the complicated "ghost tables" that are needed to create a fully responsive gmail email into customizable tags. 

We'll be working through these issues in v2, however we're not supporting v1 anymore. We're more than happy to merge any PRs on our v1.0.0 branch. Hope this helps clarify. Thanks!
