### ISSUE TITLE
[Question] Class Visibility and Gmail

### ISSUE THREAD

**Issue by AlexL5** [zurb/foundation-emails#140]
Hello,

Is there any date expected for class visibilty support in gmail ? 

Thanks.

**Comment by tdhartwick** [comment]
Gmail is a tricky beast, since it strips out everything in the head of HTML emails, aka all of the media queries, it makes it difficult to show/hide things for gmail. As of now this isn't supported, but there's a conversation happening on this issue: https://github.com/zurb/foundation-emails/issues/201

Thanks!
