### ISSUE TITLE
"Cannot GET /" on localhost:3000

### ISSUE THREAD

**Issue by allenwoot** [zurb/foundation-emails#38]
I'm getting the text Cannot GET / on npm test when the browser opens up localhost:3000.

This is in the develop branch, and the master branch worked for me.

**Comment by gakimball** [comment]
This was either happening because the testing folder had no `index.html` file, or BrowserSync launched before Gulp was done processing pages.

Either way, today we put out a [release candidate](https://github.com/zurb/foundation-emails/releases/tag/v2.0.0-rc.1) for Foundation for Emails 2, and all future testing will happen in the [dedicated template repo](https://github.com/zurb/foundation-emails-template).

If you encounter any issues with the new standalone template, let us know. :)
